#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

OS_ARCH_LINUX="arm64 amd64"
KUBE_BUILD_PLATFORMS="linux/arm64 linux/amd64"
K8S_BASE="k8s.io/component-base"

mkdir -p output/bin
if [ -n "$VERSION" ]; then
    TAG=$VERSION
fi

buildDate=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
GOLDFLAGS="
    -X ${K8S_BASE}/version.gitVersion=${TAG}
    -X ${K8S_BASE}/version.gitCommit=${COMMIT}
    -X ${K8S_BASE}/version.gitTreeState=${GIT_TREE_STATE}
    -X ${K8S_BASE}/version.buildDate=${buildDate}
"

build/run.sh make kubelet KUBE_BUILD_PLATFORMS="${KUBE_BUILD_PLATFORMS}"

for ARCH in ${OS_ARCH_LINUX}; do
        mv _output/dockerized/bin/linux/$ARCH/kubelet .
        if [ $ARCH = "amd64" ]; then
            ./kubelet --version
        fi
        tar -cvzf output/bin/kubelet-$TAG-$ARCH.tar.gz kubelet && rm kubelet
done

sha256sum output/bin/* > output/bin/sha256sum.txt

rm -rf _output/

echo Built ${TAG}

if [ -d "output/bin" ] && [ "$(ls -A output/bin)" ]; then
    echo "The directory output/bin exists and is not empty."
    ls -lR output/bin
else
    echo "The directory output/bin does not exist or is empty."
    exit 1
fi